In [7]:
import pandas as pd

info2023 = pd.read_csv('每日各站進出站人數2023.csv')
info2023
siteInfo = pd.read_csv('車站基本資料集.csv')
siteInfo
df1 = pd.merge(info2023,siteInfo,left_on='staCode',right_on='code')
df1

,trnOpDate,staCode,gateInComingCnt,gateOutGoingCnt,Unnamed: 0,code,站名,地址
0,20230101,900,8030,8241,0,900,基隆,基隆市仁愛區港西街5號
1,20230101,910,1017,1326,1,910,三坑,基隆市仁愛區德厚里龍安街 206 號
2,20230101,920,1400,1705,2,920,八堵,基隆市暖暖區八南里八堵路 142 號
3,20230101,930,3558,4398,3,930,七堵,基隆市七堵區長興里東新街 2 號
4,20230101,940,1509,1815,4,940,百福,基隆市七堵區堵南里明德三路 1 之 1 號
...,...,...,...,...,...,...,...,...
86604,20231231,7360,7916,8252,238,7360,瑞芳,新北市瑞芳區龍潭里明燈路三段 82 號
86605,20231231,7361,164,195,239,7361,海科館,基隆市中正區長潭里
86606,20231231,7362,652,720,240,7362,八斗子,新北市瑞芳區建基路2段121號隔壁 砂子里省道臺 2 線 (與新北市瑞芳區交界處、無站房)
86607,20231231,7380,1526,656,241,7380,四腳亭,新北市瑞芳區吉慶里中央路 65 號
86608,20231231,7390,576,447,242,7390,暖暖,基隆市暖暖區暖暖里暖暖街 51 號

In [10]:
df2 = df1[['trnOpDate','staCode','站名','gateInComingCnt','gateOutGoingCnt','地址']]
df2.columns = ['日期','code','站名','進站','出站','地址']
df2

,日期,code,站名,進站,出站,地址
0,20230101,900,基隆,8030,8241,基隆市仁愛區港西街5號
1,20230101,910,三坑,1017,1326,基隆市仁愛區德厚里龍安街 206 號
2,20230101,920,八堵,1400,1705,基隆市暖暖區八南里八堵路 142 號
3,20230101,930,七堵,3558,4398,基隆市七堵區長興里東新街 2 號
4,20230101,940,百福,1509,1815,基隆市七堵區堵南里明德三路 1 之 1 號
...,...,...,...,...,...,...
86604,20231231,7360,瑞芳,7916,8252,新北市瑞芳區龍潭里明燈路三段 82 號
86605,20231231,7361,海科館,164,195,基隆市中正區長潭里
86606,20231231,7362,八斗子,652,720,新北市瑞芳區建基路2段121號隔壁 砂子里省道臺 2 線 (與新北市瑞芳區交界處、無站房)
86607,20231231,7380,四腳亭,1526,656,新北市瑞芳區吉慶里中央路 65 號
86608,20231231,7390,暖暖,576,447,基隆市暖暖區暖暖里暖暖街 51 號

In [11]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 86609 entries, 0 to 86608
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   日期      86609 non-null  int64
 1   code    86609 non-null  int64
 2   站名      86609 non-null  object
 3   進站      86609 non-null  int64
 4   出站      86609 non-null  int64
 5   地址      86609 non-null  object
dtypes: int64(4), object(2)
memory usage: 4.0+ MB

In [16]:
df2.loc[:,'日期'] = pd.to_datetime(df2['日期'].astype(str))

In [19]:
df2.query('站名=="臺北"')

              日期  code  站名     進站     出站                 地址
10    2023-01-01  1000  臺北  73133  51866  臺北市中正區黎明里北平西路 3 號
248   2023-01-02  1000  臺北  46655  55836  臺北市中正區黎明里北平西路 3 號
486   2023-01-03  1000  臺北  49330  51685  臺北市中正區黎明里北平西路 3 號
724   2023-01-04  1000  臺北  47850  47523  臺北市中正區黎明里北平西路 3 號
961   2023-01-05  1000  臺北  48663  48134  臺北市中正區黎明里北平西路 3 號
...          ...   ...  ..    ...    ...                ...
85432 2023-12-27  1000  臺北  62482  60673  臺北市中正區黎明里北平西路 3 號
85668 2023-12-28  1000  臺北  62564  59950  臺北市中正區黎明里北平西路 3 號
85905 2023-12-29  1000  臺北  81667  73713  臺北市中正區黎明里北平西路 3 號
86143 2023-12-30  1000  臺北  77090  67886  臺北市中正區黎明里北平西路 3 號
86381 2023-12-31  1000  臺北  62141  90865  臺北市中正區黎明里北平西路 3 號

[365 rows x 6 columns]

In [21]:
df2.query('進站>=30000')

              日期  code  站名     進站     出站                    地址
10    2023-01-01  1000  臺北  73133  51866     臺北市中正區黎明里北平西路 3 號
78    2023-01-01  3300  臺中  37255  33837    臺中市中區綠川里臺灣大道一段 1 號
248   2023-01-02  1000  臺北  46655  55836     臺北市中正區黎明里北平西路 3 號
486   2023-01-03  1000  臺北  49330  51685     臺北市中正區黎明里北平西路 3 號
724   2023-01-04  1000  臺北  47850  47523     臺北市中正區黎明里北平西路 3 號
...          ...   ...  ..    ...    ...                   ...
86381 2023-12-31  1000  臺北  62141  90865     臺北市中正區黎明里北平西路 3 號
86383 2023-12-31  1020  板橋  30751  35205  新北市板橋區新民里縣民大道二段 7 號
86389 2023-12-31  1080  桃園  37128  30865      桃園市桃園區武陵里中正路 1 號
86391 2023-12-31  1100  中壢  34694  29912    桃園市中壢區石頭里中和路 139 號
86449 2023-12-31  3300  臺中  41206  47244    臺中市中區綠川里臺灣大道一段 1 號

[632 rows x 6 columns]

In [22]:
df2.query('進站>=30000 and 站名=="中壢"')

              日期  code  站名     進站     出站                  地址
9756  2023-02-11  1100  中壢  30445  30366  桃園市中壢區石頭里中和路 139 號
9994  2023-02-12  1100  中壢  32030  34085  桃園市中壢區石頭里中和路 139 號
16629 2023-03-12  1100  中壢  31083  32787  桃園市中壢區石頭里中和路 139 號
26584 2023-04-23  1100  中壢  30391  31311  桃園市中壢區石頭里中和路 139 號
51510 2023-08-06  1100  中壢  30734  30454  桃園市中壢區石頭里中和路 139 號
53173 2023-08-13  1100  中壢  32062  31642  桃園市中壢區石頭里中和路 139 號
59806 2023-09-10  1100  中壢  34619  35486  桃園市中壢區石頭里中和路 139 號
60990 2023-09-15  1100  中壢  30546  28707  桃園市中壢區石頭里中和路 139 號
61463 2023-09-17  1100  中壢  32112  33915  桃園市中壢區石頭里中和路 139 號
64075 2023-09-28  1100  中壢  32074  29845  桃園市中壢區石頭里中和路 139 號
64788 2023-10-01  1100  中壢  30126  31762  桃園市中壢區石頭里中和路 139 號
65965 2023-10-06  1100  中壢  31818  29896  桃園市中壢區石頭里中和路 139 號
66440 2023-10-08  1100  中壢  33036  33661  桃園市中壢區石頭里中和路 139 號
68107 2023-10-15  1100  中壢  31288  32065  桃園市中壢區石頭里中和路 139 號
69772 2023-10-22  1100  中壢  30914  32127  桃園市中壢區石頭里中和路 139 號
73096 2023-11-05  1100  中壢  31242  32221  桃園市中壢區石頭里中和路 139 號
74285 2023-11-10  1100  中壢  31247  30078  桃園市中壢區石頭里中和路 139 號
74522 2023-11-11  1100  中壢  32571  32546  桃園市中壢區石頭里中和路 139 號
74761 2023-11-12  1100  中壢  34169  35707  桃園市中壢區石頭里中和路 139 號
75949 2023-11-17  1100  中壢  30968  29608  桃園市中壢區石頭里中和路 139 號
76426 2023-11-19  1100  中壢  32773  34296  桃園市中壢區石頭里中和路 139 號
77614 2023-11-24  1100  中壢  30202  29296  桃園市中壢區石頭里中和路 139 號
80935 2023-12-08  1100  中壢  31863  30058  桃園市中壢區石頭里中和路 139 號
81172 2023-12-09  1100  中壢  35420  36564  桃園市中壢區石頭里中和路 139 號
81409 2023-12-10  1100  中壢  38908  40380  桃園市中壢區石頭里中和路 139 號
82595 2023-12-15  1100  中壢  31527  29916  桃園市中壢區石頭里中和路 139 號
82833 2023-12-16  1100  中壢  30111  30917  桃園市中壢區石頭里中和路 139 號
83071 2023-12-17  1100  中壢  31855  33063  桃園市中壢區石頭里中和路 139 號
85915 2023-12-29  1100  中壢  31898  29937  桃園市中壢區石頭里中和路 139 號
86391 2023-12-31  1100  中壢  34694  29912  桃園市中壢區石頭里中和路 139 號

In [31]:
df2.query('日期 == "2023-09-10" and 站名 == "三坑"')

/tmp/ipykernel_7528/1112921958.py:1: FutureWarning: The behavior of 'isin' with dtype=datetime64[ns] and castable values (e.g. strings) is deprecated. In a future version, these will not be considered matching by isin. Explicitly cast to the appropriate dtype before calling isin instead.
  df2.query('日期 == "2023-09-10" and 站名 == "三坑"')

              日期  code  站名    進站    出站                  地址
59787 2023-09-10   910  三坑  1294  1289  基隆市仁愛區德厚里龍安街 206 號